name: speedtest
services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:amd64-latest
    container_name: speedtest
    volumes:
      - ${INSTALL_DIRECTORY}/config/speedtest:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */3 * * *"
      - PRUNE_RESULTS_OLDER_THAN=7
      - PUBLIC_DASHBOARD=true
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speed.local.shanewilson.co.u\
        k`)"
      - "traefik.http.routers.speedtest.entrypoints=https"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
