name: watchtower
services:
  watchtower:
    image: containrrr/watchtower:amd64-latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
