name: uptime
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    volumes:
      - ${INSTALL_DIRECTORY}/config/uptime:/app/data
    networks:
      - proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`status.local.shanewilson.co.uk`)"
      - "traefik.http.routers.uptime.entrypoints=https"
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
