name: jellyfin
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:amd64-latest
    container_name: jellyfin
    volumes:
      - ${INSTALL_DIRECTORY}/config/jellyfin:/config
      - ${MEDIA_DIRECTORY}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.shanewilson.co\
        .uk`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
