name: gluetun
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - PORT_FORWARD_ONLY=on
      - SERVER_COUNTRIES=Comoros
      - VPN_PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=172.18.0.0/24
    ports:
      - '0.0.0.0:8003:8000/tcp'
      - '0.0.0.0:8081:8081/tcp'
      - '0.0.0.0:8191:8191/tcp'
      - '0.0.0.0:8388:8388/tcp'
      - '0.0.0.0:8388:8388/udp'
      - '0.0.0.0:8888:8888/tcp'
      - '0.0.0.0:9696:9696/tcp'
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.shanewilson.co\
        .uk`)"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

      - "traefik.http.routers.qbittorrent.rule=Host(`qbit.local.shanewilson.co.\
        uk`)"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"

      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.local.shanew\
        ilson.co.uk`)"
      - "traefik.http.routers.flaresolverr.service=flaresolverr"
      - "traefik.http.routers.flaresolverr.entrypoints=https"
      - "traefik.http.routers.flaresolverr.tls=true"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
